# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Java Gems
url: https://www.edgriebel.com
name: Java Gems
description: > # this means to ignore newlines until "baseurl:"
  Just another Jekyll site

show_downloads: false

twitter_username: edgriebel
github_username: edgriebel
linkedin_username: edgriebel

# Build settings
markdown: kramdown
# theme: jekyll-theme-time-machine ## bug in post title uses site title
# pretty plain! theme: jekyll-theme-slate
# Too Minimal!! theme: jekyll-theme-minimal
# theme: jekyll-theme-minimal
# theme: jekyll-theme-primer
# theme: minima
# theme: jekyll-theme-tactile
# theme: jekyll-theme-cayman
theme: jekyll-theme-modernist
repository: edgriebel/edgriebel.github.io

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
        
# Should this be :year-:title? /:year/:month/:title? /:year/:title? /:title?
permalink: /:categories/:year-:title/
